spring.application.name=empleados
spring.datasource.url=jdbc:mysql://localhost:3306/parameta_db
spring.datasource.username=root
spring.datasource.password=Parameta123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true